defaults:
  - model: v1_light
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

debug: False

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# personal settings
data_dir: ${oc.env:data_dir}
wandb_api_key: ${oc.env:wandb_api_key}

batch_size: 64
overlap_ratio: 0